### ISSUE TITLE
Pipe symbol looks like forward-slash

### ISSUE THREAD

**Issue by devholland** [atelierbram/Base2Tone-VSCode-Themes#9]
Hi there, I really love your Base2Tone themes. The only thing that really distracts me is that the pipe symbol `|` looks like a forward-slash `/` when writing Bash scripts. Would it be possible to adjust that somehow?

![image](https://github.com/atelierbram/Base2Tone-VSCode-Themes/assets/62172067/3e8449a3-b819-4d6a-82f1-cd22c0b8e67d)

**Comment by atelierbram** [comment]
Thanks and thanks for the info, but I can't reproduce this issue. The syntax highlighting seems off as well in your screenshot, it should look more like this:

![](https://i.imgur.com/gmnFnQz.jpg)

**Comment by devholland** [comment]
Thanks for your reply. It does look normally in strings for me, it only happens when written outside of strings in e.g. a `test.sh` file.

It's the same symbol `|` in both lines, second one looks normal because it's in a string. First line is irritating though:
![image](https://github.com/atelierbram/Base2Tone-VSCode-Themes/assets/62172067/102896ab-1358-4b1f-bcdb-974a34bc3736)

**Comment by atelierbram** [comment]
@devholland thanks for the feedback, but this issue is still mysterious to me. Can you maybe make a gist of the file you are testing, also for me to check on? Something like this maybe: https://gist.github.com/atelierbram/26f8387382633dc6748ce3979da16c13 ,  you might want to check that one as well. Like I wrote earlier, it works for me on a fresh installation of VSCode (MacOS silicon).

**Comment by devholland** [comment]
Thanks for helping me out here, really appreciating it since I love the Base2Tone themes. I haven't tried it with a fresh installation yet. I tried to disable some Bash related extensions like **Bash IDE**, but nothing helped so far. I have so many other themes installed and none of them does this italic-pipe thing, it only happens with Base2Tone.

Here's a gist of one of the files I'm experiencing it:
https://gist.github.com/devholland/1bee5936b7d805773d6e8c0ee3654605

It really gives me a headache, because it looks like this for me:
![image](https://github.com/atelierbram/Base2Tone-VSCode-Themes/assets/62172067/d23f6898-3d31-45ab-a243-e7b0d1470c6e)

If nothing helps I'll try a fresh VSCode installation tomorrow evening.

**Comment by atelierbram** [comment]
Getting closer now: choosing "Consolas" in "Settings" as a font gets me this result. So probably one of the settings in the themes where you get: `"fontStyle": "italic"` in combination with the use of a monospace font with true italics, like Consolas is making the pipe symbol italic. So next is figuring out which of the 45 instances of `"fontStyle": "italic"` should be deleted from the themes ... to be continued.

**Comment by devholland** [comment]
Awesome, thank you very much. I'm currently using `JetBrainsMono Nerd Font` in VSCode, so maybe it's the same problem there as with Consolas. I'll try it later and come back to you.

**Comment by devholland** [comment]
Yes, it works! :D The pipe symbol looks normally now. Thank you very much.

![image](https://github.com/atelierbram/Base2Tone-VSCode-Themes/assets/62172067/7688bbaa-2c43-4a36-995c-8e76c90a537e)

**Comment by atelierbram** [comment]
Glad to be of help. BTW I will update the Readme's of my VS Code themes in a bit to encourage people to disable the coloration of matching brackets in settings, because it doesn't fit these themes at all, ... looks terrible in my eyes. The last screenshot of your `pattern.sh` suggests it's still on in your setup, but note these bracket colors are not from the theme files, and look the same across different themes. Not telling you what to do of course but just a heads up, see also [this issue](https://github.com/microsoft/vscode/issues/149006).

```bash
    "editor.matchBrackets": "always",
    "editor.bracketPairColorization.enabled": false,
    "editor.language.colorizedBracketPairs": [["(", ")"]],
```

Anyway, take care!
